config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get  '/about',            to: 'static_pages#about'
  get  '/contact',          to: 'static_pages#contact'
  get  '/privacy_policy',   to: 'static_pages#privacy_policy'
  get  '/terms_of_service', to: 'static_pages#terms_of_service'
  get  '/signup',           to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get    :withdrawal_confirmation, :following, :followers
      delete :withdrawal_destroy
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :posts, only: %i[index show create destroy] do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
  resources :relationships, only: %i[create destroy]
  resources :matching, only: [:index]
  resources :chat_rooms, only: %i[create show]
  resources :notifications, only: %i[index update]
  resources :lend_farmlands do
    resources :favorites, only: %i[create destroy]
  end
  resources :rent_farmlands
  resources :consults, only: %i[index create show]
end

app/models/rent_farmland.rb
class RentFarmland < ApplicationRecord
  include EnumForDistrictSelection

  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :rent_philosophy, length: { maximum: 1000 }
  validates :rent_other_term, length: { maximum: 500 }
  enum rent_municipality: { 茅野市: 0, 諏訪郡原村: 1, 諏訪郡富士見町: 2, 田畑の場所を限定しない: 3 }, _prefix: true
  enum rent_area: { 五畝未満: 0, 五畝〜一反: 1, 一反〜一反五畝: 2, 一反五畝〜二反: 3, 二反〜二反五畝: 4, 二反五畝以上: 5 }, _prefix: true
  enum rent_field_type: { 田: 0, 畑: 1, その他: 2 }, _prefix: true
  enum borrow_immediately: { すぐに借りたい: 0, すぐではなくて良いけど借りたい: 1 }
  enum rent_desired_year: { 一年未満: 0, 一年〜二年: 1, 二年〜三年: 2, 三年以上: 3, 現時点では未定: 4 }, _prefix: true
  enum renting_term: { 無償を希望: 0, 条件付き無償を希望: 1, 有償で構わない: 2 }
  validates :rent_municipality,
            inclusion: { in: RentFarmland.rent_municipalities.keys }
  validates :rent_area,
            inclusion: { in: RentFarmland.rent_areas.keys }
  validates :rent_field_type,
            inclusion: { in: RentFarmland.rent_field_types.keys }
  validates :borrow_immediately,
            inclusion: { in: RentFarmland.borrow_immediatelies.keys }
  validates :rent_desired_year,
            inclusion: { in: RentFarmland.rent_desired_years.keys }
  validates :renting_term,
            inclusion: { in: RentFarmland.renting_terms.keys }
end

app/controllers/rent_farmlands_controller.rb
class RentFarmlandsController < ApplicationController
  before_action :login_required
  before_action :correct_user, only: :destroy
  before_action :set_rent_farmland, only: %i[show edit update destroy]

  def index
    @rent_farmlands = RentFarmland.page(params[:page]).per(5)
    @chino_rent_indexes = RentFarmland.where(rent_municipality: '茅野市').page(params[:page]).per(5)
    @hara_rent_indexes = RentFarmland.where(rent_municipality: '諏訪郡原村').page(params[:page]).per(5)
    @fujimi_rent_indexes = RentFarmland.where(rent_municipality: '諏訪郡富士見町').page(params[:page]).per(5)
    @not_limited_indexes = RentFarmland.where(rent_municipality: '田畑の場所を限定しない').page(params[:page]).per(5)
  end

  def show
  end

  def new
    @rent_farmland = RentFarmland.new
  end

  def create
    @rent_farmland = current_user.rent_farmlands.build(rent_farmland_params)
    if @rent_farmland.save
      flash[:success] = '借りたい農地の情報を登録しました'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @rent_farmland.update(rent_farmland_params)
      flash[:success] = '借りたい農地の情報を編集しました'
      redirect_to lend_farmlands_path
    else
      render 'edit'
    end
  end

  def destroy
    @rent_farmland.destroy
    flash[:success] = '借りたい農地の情報を削除しました'
    redirect_to request.referrer || root_url
  end

  private

    def rent_farmland_params
      params.require(:rent_farmland).permit(
        :rent_philosophy,
        :rent_municipality,
        :rent_chino,
        :rent_hara,
        :rent_fujimi,
        :rent_area,
        :rent_field_type,
        :rent_desired_year,
        :borrow_immediately,
        :renting_term,
        :rent_other_term,
      )
    end

    def correct_user
      @rent_farmland = current_user.rent_farmlands.find_by(id: params[:id])
      redirect_to rooit_url if @rent_farmland.nil?
    end

    def set_rent_farmland
      @rent_farmland = RentFarmland.find(params[:id])
    end
end

app/helpers/rent_farmlands_helper.rb
module RentFarmlandsHelper
end

app/views/rent_farmlands/_rent_farmland.html.erb
<div class="mb-4">
  <div class="row farmland-hr">
    <div class="col-md-12">
      <div class="rend_farmland-index">
        <div class="farmland-user-ballon">
          <div class="farmland-avatar">
            <% if rent_farmland.user.avatar.attached? %>
              <%= image_tag rent_farmland.user.avatar, class: "farmland-avatar" %>
            <% else %>
              <img src="/assets/profile_default_img_128.png" class="farmland-default-avatar">
            <% end %>
          </div>
          <div class="farmland-user-name">
            <%= link_to rent_farmland.user.name, user_path(rent_farmland.user) %>
          </div>
        </div>
        <div class="lend-or-rent-heading">
          <h5>農地を借りたい!!</h5>
        </div>
        <div>
          <table>
            <tr>
              <th>借りたい田畑の場所</th>
              <td>
                <%= rent_farmland.rent_municipality %>
                <% if rent_farmland.rent_municipality_before_type_cast == 0 %>
                  <%= rent_farmland.rent_chino %>
                <% elsif rent_farmland.rent_municipality_before_type_cast == 1 %>
                  <%= rent_farmland.rent_hara %>
                <% elsif rent_farmland.rent_municipality_before_type_cast == 2 %>
                  <%= rent_farmland.rent_fujimi %>
                <% end %>
              </td>
            </tr>
            <tr>
              <th>借りたい田畑の面積</th>
              <td><%= rent_farmland.rent_area %></td>
            </tr>
            <tr>
              <th>借りたい田畑の種類</th>
              <td><%= rent_farmland.rent_field_type %></td>
            </tr>
            <tr>
              <th>すぐに借りたいか</th>
              <td><%= rent_farmland.borrow_immediately %></td>
            </tr>
          </table>
        </div>
        <div class="col-md-12">
          <% if current_user?(rent_farmland.user) %>
            <div class="row">
              <div class="mr-2">
                <%= link_to "編集", edit_rent_farmland_path(rent_farmland), class: "btn btn-outline-secondary" %>
              </div>
              <div class="farmland-destroy">
                <%= link_to "削除", rent_farmland_path(rent_farmland), method: :delete, class: "btn btn-outline-secondary", data: { confirm: '本当に削除してもよろしいですか？'} %>
              </div>
            </div>
          <% end %>
          <div class="float-right my-3">
            <%= link_to "詳しく見る", rent_farmland_path(rent_farmland), class: "btn btn-dark" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rent_farmlands/_rent_farmlands_form.html.erb
<ul class="form-mes">
  <li>最後の「その他条件」を除いてすべて入力必須項目です</li>
  <li>条件の選択でどれにも当てはまらなかったり、付け加えたいことがありましたら「その他条件」の欄に記入してください</li>
</ul>
<%= form_with(model: @rent_farmland, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :哲学, { class: 'form-label' } %>
  <%= f.text_area :rent_philosophy, placeholder: '自分の農業に対する想いや、こんな風に使いたいなど、自由に自身の世界観を書いてください', class: "mb-2 lend-philo"%>
  <div class="form-group row">
    <div class="col">
      <%= f.label :rent_municipality, '借りたい田畑の市町村', { class: 'form-label' } %>
    </div>
    <div class="col-md-12 btn-group btn-group-toggle" data-toggle="buttons mb-2">
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :rent_municipality, '茅野市', {} %> 茅野市
      </label>
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :rent_municipality, '諏訪郡原村', {} %> 諏訪郡原村
      </label>
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :rent_municipality, '諏訪郡富士見町', {} %> 諏訪郡富士見町
      </label>
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :rent_municipality, '田畑の場所を限定しない', {} %> 田畑の場所を限定しない
      </label>
    </div>
  </div>
  <%= f.label :いま選んだ市町村名の中から借りたい田畑の地区を選択してください, { class: 'form-label' }  %>
  <div class="row mb-3">
    <div class="col">
      <%= f.select :rent_chino, RentFarmland.rent_chinos.keys, {} %>
    </div>
    <div class="col">
      <%= f.select :rent_hara, RentFarmland.rent_haras.keys, {} %>
    </div>
    <div class="col">
      <%= f.select :rent_fujimi, RentFarmland.rent_fujimis.keys, {} %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col">
      <%= f.label :rent_area, '借りたい田畑の面積', { class: 'form-label' } %>
    </div>
    <div class="col-md-12 btn-group btn-group-toggle mb-2" data-toggle="buttons">
      <label class="btn btn-outline-dark lend-area" style="width:50%">
        <%= f.radio_button :rent_area, '五畝未満', {} %> 五畝未満
      </label>
      <label class="btn btn-outline-dark lend-area" style="width:50%">
        <%= f.radio_button :rent_area, '五畝〜一反', {} %> 五畝〜一反
      </label>
      <label class="btn btn-outline-dark lend-area" style="width:50%">
        <%= f.radio_button :rent_area, '一反〜一反五畝', {} %> 一反〜一反五畝
      </label>
      <label class="btn btn-outline-dark lend-area" style="width:50%">
        <%= f.radio_button :rent_area, '一反五畝〜二反', {} %> 一反五畝〜二反
      </label>
      <label class="btn btn-outline-dark lend-area" style="width:50%">
        <%= f.radio_button :rent_area, '二反〜二反五畝', {} %> 二反〜二反五畝
      </label>
      <label class="btn btn-outline-dark lend-area" style="width:50%">
        <%= f.radio_button :rent_area, '二反五畝以上', {} %> 二反五畝以上
      </label>
    </div>
  </div>
  <div class="form-group row">
    <div class="col">
      <%= f.label :rent_field_type, '借りたい農地の種類', { class: 'form-label' } %>
    </div>
    <div class="col-md-12 btn-group btn-group-toggle mb-2" data-toggle="buttons">
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :rent_field_type, '田', {} %> 田
      </label>
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :rent_field_type, '畑', {} %> 畑
      </label>
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :rent_field_type, 'その他', {} %> その他
      </label>
    </div>
  </div>
  <div class="form-group row">
    <div class="col">
      <%= f.label :borrow_immediately, '農地をすぐに借りたいか', { class: 'form-label' } %>
    </div>
    <div class="col-md-12 btn-group btn-group-toggle mb-2" data-toggle="buttons">
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :borrow_immediately, 'すぐに借りたい', {} %> すぐに借りたい
      </label>
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :borrow_immediately, 'すぐではなくて良いけど借りたい', {} %> すぐではなくて良いけど借りたい
      </label>
    </div>
  </div>
  <div class="form-group row">
    <div class="col">
      <%= f.label :rent_desired_year, '使用希望年数', { class: 'form-label' } %>
    </div>
    <div class="col-md-12 btn-group btn-group-toggle mb-2" data-toggle="buttons">
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :rent_desired_year, '一年未満', {} %> 一年未満
      </label>
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :rent_desired_year, '一年〜二年', {} %> 一年〜二年
      </label>
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :rent_desired_year, '二年〜三年', {} %> 二年〜三年
      </label>
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :rent_desired_year, '三年以上', {} %> 三年以上
      </label>
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :rent_desired_year, '現時点では未定', {} %> 現時点では未定
      </label>
    </div>
  </div>
  <div class="form-group row">
    <div class="col">
      <%= f.label :renting_term, '借りる条件', { class: 'form-label' } %>
    </div>
    <div class="col-md-12 btn-group btn-group-toggle mb-2" data-toggle="buttons">
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :renting_term, '無償を希望', {} %> 無償を希望
      </label>
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :renting_term, '条件付き無償を希望', {} %> 条件付き無償を希望
      </label>
      <label class="btn btn-outline-dark" style="width:50%">
        <%= f.radio_button :renting_term, '有償で構わない', {} %> 有償で構わない
      </label>
    </div>
  </div>
  <%= f.label :その他の条件, { class: 'form-label' } %>
  <%= f.text_area :rent_other_term, placeholder: '借りることに関し、付け加えたい情報があればここに書いてください', class: "mb-2 lend-other-term"%>
  <%= f.submit yield(:button_text), class: "btn btn-dark" %>
<% end %>
</div>

app/views/rent_farmlands/edit.html.erb
<% provide(:title, 'Rent farmlands') %>
<% provide(:button_text, '借りたい農地の情報を変更する') %>
<div class="container py-4">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1>借りたい農地情報の編集</h1>
      <%= render 'rent_farmland_form' %>
    </div>
  </div>
</div>

app/views/rent_farmlands/index.html.erb
<% provide(:title, 'Rent farmlands list') %>
<h1>I'd like to rent a field</h1>
<div class="container py-4">
  <div class="row">
    <div class="col-md-12">
      <div class="card-group">
        <div class="card-body">
          <ul class="tab-list">
            <li class="tab tab-active">全てを表示</li>
            <li class="tab">茅野市の農地</li>
            <li class="tab">原村の農地</li>
            <li class="tab">富士見町の農地</li>
            <li class="tab">田畑の場所を限定しない</li>
          </ul>
          <br>
          <div class="tabbox-contents">
            <div class="tabbox box-show">
              <div class="lend_farmland-h mb-3">
                <%= link_to '農地を借りたい', new_rent_farmland_path, class: "btn btn-primary w-100 mb-3" %>
              </div>
              <%= render @rent_farmlands %>
            </div>
            <div class="tabbox">
              <div class="lend_farmland-hr mb-3">
                <%= link_to '農地を借りたい', new_rent_farmland_path, class: "btn btn-primary w-100 mb-3"%>
              </div>
              <%= render partial: 'rent_farmlands/rent_farmland', collection: @chino_rent_indexes, as: :rent_farmland %>
            </div>
            <div class="tabbox">
              <div class="lend_farmland-hr mb-3">
                <%= link_to '農地を借りたい', new_rent_farmland_path, class: "btn btn-primary w-100 mb-3"  %>
              </div>
              <%= render partial: 'rent_farmlands/rent_farmland', collection: @hara_rent_indexes, as: :rent_farmland %>
            </div>
            <div class="tabbox">
              <div class="lend_farmland-hr mb-3">
                <%= link_to '農地を借りたい', new_rent_farmland_path, class: "btn btn-primary w-100 mb-3"  %>
              </div>
              <%= render partial: 'rent_farmlands/rent_farmland', collection: @fujimi_rent_indexes, as: :rent_farmland %>
            </div>
            <div class="tabbox">
              <div class="lend_farmland-hr mb-3">
                <%= link_to '農地を借りたい', new_lend_farmland_path, class: "btn btn-primary w-100 mb-3"  %>
              </div>
              <%= render partial: 'rent_farmlands/rent_farmland', collection: @not_limited_indexes, as: :rent_farmland %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(function() {
  $('.tab').click(function(){
  $('.tab-active').removeClass('tab-active');
  $(this).addClass('tab-active');
  $('.box-show').removeClass('box-show');
  const index = $(this).index();
  $('.tabbox').eq(index).addClass('box-show');
  });
  });
</script>

app/views/rent_farmlands/new.html.erb
<% provide(:title, 'Rent farmlands') %>
<% provide(:button_text, 'この内容で登録する') %>
<div class="container py-4">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1 class="mb-4">借りたい農地の情報登録</h1>
      <%= render 'rent_farmlands_form' %>
    </div>
  </div>
</div>

app/views/rent_farmlands/show.html.erb
<%= provide(:title, 'RentFarmland details' ) %>
<h1>Rent farmland details</h1>
<div class="py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="card-group">
          <div class="card-body">
            <div class="row">
              <div class="mypage-avatar">
                <% if @rent_farmland.user.avatar.attached? %>
                  <div class="avatar">
                    <%= image_tag @rent_farmland.user.avatar, class: "avatar" %>
                  </div>
                <% else %>
                  <img src="/assets/profile_default_img_128.png" class="default-avatar">
                <% end %>
              </div>
              <div class="col-md-10">
                <div class="mypage-name">
                  <h3><%= link_to @rent_farmland.user.name, user_path(@rent_farmland.user) %></h3>
                </div>
                &nbsp;
                <% if @rent_farmland.user.address.present? %>
                  <div class="user-address">
                    <%= @rent_farmland.user.address %>在住
                  </div>
                <% end %>
                <div class="mypage-self_info">
                  <%= @rent_farmland.user.self_info %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-4">
            <div class="card-group rent_philosophy-box">
              <div class="card-body">
                <div class="rent_philosophy-for-show mb-3">
                  私の農業哲学
                </div>
                <%= @rent_farmland.rent_philosophy %>
              </div>
            </div>
          </div>
          <div class="col-md-8">
            <div class="card-group">
              <div class="card-body">
                <div>
                  <table>
                    <tr>
                      <th>借りたい田畑の場所</th>
                      <td>
                        <%= @rent_farmland.rent_municipality %>
                        <% if @rent_farmland.rent_municipality_before_type_cast == 0 %>
                          <%= @rent_farmland.rent_chino %>
                        <% elsif @rent_farmland.rent_municipality_before_type_cast == 1 %>
                          <%= @rent_farmland.rent_hara %>
                        <% elsif @rent_farmland.rent_municipality_before_type_cast == 2 %>
                          <%= @rent_farmland.rent_fujimi %>
                        <% end %>
                      </td>
                    </tr>
                    <tr>
                      <th>借りたい田畑の面積</th>
                      <td><%= @rent_farmland.rent_area %></td>
                    </tr>
                    <tr>
                      <th>借りたい農地の種類</th>
                      <td><%= @rent_farmland.rent_field_type %></td>
                    </tr>
                    <tr>
                      <th>農地をすぐに借りたいか</th>
                      <td><%= @rent_farmland.borrow_immediately %></td>
                    </tr>
                    <tr>
                      <th>使用希望年数</th>
                      <td><%= @rent_farmland.rent_desired_year %></td>
                    </tr>
                    <th>借りる条件</th>
                    <td><%= @rent_farmland.renting_term %></td>
                  </tr>
                  <% if @rent_farmland.rent_other_term.present? %>
                    <tr>
                      <th>その他条件</th>
                      <td><%= @rent_farmland.rent_other_term %></td>
                    </tr>
                  <% end %>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <% if current_user?(@rent_farmland.user) %>
          <div class="row">
            <div class="mr-2">
              <%= link_to "編集", edit_rent_farmland_path(@rent_farmland), class: "btn btn-outline-secondary" %>
            </div>
            <div class="farmland-destroy">
              <%= link_to "削除", rent_farmland_path(@rent_farmland), method: :delete, class: "btn btn-outline-secondary", data: { confirm: '本当に削除してもよろしいですか？'} %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>