config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get  '/about',            to: 'static_pages#about'
  get  '/contact',          to: 'static_pages#contact'
  get  '/privacy_policy',   to: 'static_pages#privacy_policy'
  get  '/terms_of_service', to: 'static_pages#terms_of_service'
  get  '/signup',           to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get    :withdrawal_confirmation, :following, :followers
      delete :withdrawal_destroy
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :posts, only: %i[index show create destroy] do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
  resources :relationships, only: %i[create destroy]
  resources :matching, only: [:index]
  resources :chat_rooms, only: %i[create show]
  resources :notifications, only: %i[index update]
  resources :lend_farmlands do
    resources :favorites, only: %i[create destroy]
  end
  resources :rent_farmlands
  resources :consults, only: %i[index create show]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
    if logged_in?
      @post = current_user.posts.build
      @feed_items = current_user.feed.page(params[:feed_page]).per(10)
      @notifications = current_user.passive_notifications.page(params[:page]).per(5)
      favorites = Favorite.where(user_id: current_user.id).pluck(:lend_farmland_id)
      @favorite_list = LendFarmland.find(favorites)
      #@favorite_items = Kaminari.paginate_array(@favorite_list).page(params[:favorite_page]).per(1)
      gon.lend_farmlands = LendFarmland.all
      gon.favorite_list = LendFarmland.find(favorites)
    end
  end

  def about
  end

  def contact
  end

  def privacy_policy
  end

  def terms_of_service
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="container">
  <% provide(:title, "about") %>
  <h1>はじめてご利用の方</h1>
  <p>8gatake farmは....</p>
  <%= link_to 'アカウント作成', signup_path, class: "btn btn-primary" %>
</div>

app/views/static_pages/contact.html.erb
  <% provide(:title, "contact") %>
  <h1>お問い合わせ</h1>
  <p>当サイトについて何かご不明な点があれば、以下の問い合わせフォームよりご連絡ください。</p>

app/views/static_pages/privacy_policy.html.erb
<% provide(:title, "privacy_policy") %>
<h1>プライバシーポリシー</h1>
<p></p>

app/views/static_pages/terms_of_service.html.erb
<% provide(:title, "terms_of_service") %>
<h1>利用規約</h1>
<p></p>

app/views/static_pages/top.html.erb
<% if logged_in? %>
  <div class="container py-4">
    <div class="row">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-12">
            <div class="card-group">
              <div class="card-body">
                <div class="row">
                  <div class="mypage-avatar">
                    <% if current_user.avatar.attached? %>
                      <div class="avatar">
                        <%= image_tag current_user.avatar, class: "avatar" %>
                      </div>
                    <% else %>
                      <img src="/assets/profile_default_img_128.png" class="default-avatar">
                    <% end %>
                  </div>
                  <div class="col-md-10">
                    <div class="mypage-name">
                      <h3><%= link_to current_user.name, current_user %></h3>
                    </div>
                    <div class="mypage-self_info">
                      <%= current_user.self_info %>
                    </div>
                    <% if current_user.admin? && !current_user?(user) %>
                      <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="card-group news">
                  <div class="card-body">
                    <div class="mypage-news">
                      <% if unchecked_notifications.any? %>
                        <h5><%= link_to "お知らせが#{current_user.passive_notifications.where(checked: false).size}件あります", notifications_path %></h5>
                      <% else %>
                        <h5>お知らせはありません</h5>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="card-group">
                  <div class="card-body">
                    <ul class="tab-list">
                      <li class="tab  tab-active">フィード</li>
                      <li class="tab">気になる農地</li>
                      <li class="tab">地図で探す</li>
                      <li class="tab">相談中</li>
                    </ul>
                    <br>
                    <div class="tabbox-contents">
                      <div class="tabbox box-show">
                        <div class="col-md-12">
                          <div class="row">
                            <div class="card-body">
                              <%= render 'shared/feed' %>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="tabbox">
                        <% if @favorite_list.present? %>
                          <%= render template: 'lend_farmlands/favorite_list' %>
                        <% else %>
                          <h5 class="text-center mt-3">気になる農地はまだありません</h5>
                          <div class="text-muted text-center">（貸したい農地にあなたが「いいね」したものがここに表示されます）</div>
                        <% end %>
                      </div>
                      <div class="tabbox">
                        <% if @favorite_list.present? %>
                          <div id="map"></div>
                          <%= render template: 'static_pages/top.js.erb' %>
                        <% else %>
                          <h5 class="text-center mt-3">気になる農地はまだありません</h5>
                          <div class="text-muted text-center">（貸したい農地にあなたが「いいね」したものの地図がここに表示されます）</div>
                        <% end %>
                      </div>
                      <div class="tabbox">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <%= render 'shared/post_form' %>
      </div>
    </div>
  </div>
<% else %>
  <div class="top-image">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="top mb-2">
            Why don't you build the foot of Mt. 8gatake where everyone has a place to stay?
          </div>
        </div>
        <%= link_to 'Sign up now!', signup_path, class: "btn btn-lg btn-dark ml-3" %>
      </div>
    </div>
  </div>
<% end %>
<script>
  $(function() {
  $('.tab').click(function(){
  $('.tab-active').removeClass('tab-active');
  $(this).addClass('tab-active');
  $('.box-show').removeClass('box-show');
  const index = $(this).index();
  $('.tabbox').eq(index).addClass('box-show');
  });
  });
</script>

app/views/static_pages/top.js.erb
<script type="text/javascript">
  let map;
  let marker = [];
  let infoWindow = [];
  let markerData = gon.favorite_list;
  function initMap() {
  geocoder = new google.maps.Geocoder()
  map = new google.maps.Map(document.getElementById('map'), {
  center: { lat: 35.964321, lng: 138.217152},
  zoom: 12,
  });
  for (var i = 0; i < markerData.length; i++) {
          let id = markerData[i]['id']
  
          markerLatLng = new google.maps.LatLng({
            lat: markerData[i]['latitude'],
            lng: markerData[i]['longitude']
          });
  
          marker[i] = new google.maps.Marker({
            position: markerLatLng,
            map: map
          });
  
          infoWindow[i] = new google.maps.InfoWindow({
            content: `<a data-turbolinks="false", href='/lend_farmlands/${ id }'>${ markerData[i]['address'] }</a>`
          });
  
          markerEvent(i);
        }
      }
  
      function markerEvent(i) {
        marker[i].addListener('click', function () {
          infoWindow[i].open(map, marker[i]);
        });
      }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap"></script>