config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get  '/about',            to: 'static_pages#about'
  get  '/contact',          to: 'static_pages#contact'
  get  '/privacy_policy',   to: 'static_pages#privacy_policy'
  get  '/terms_of_service', to: 'static_pages#terms_of_service'
  get  '/signup',           to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get    :withdrawal_confirmation, :following, :followers
      delete :withdrawal_destroy
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :posts, only: %i[index show create destroy] do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
  resources :relationships, only: %i[create destroy]
  resources :matching, only: [:index]
  resources :chat_rooms, only: %i[create show]
  resources :notifications, only: %i[index update]
  resources :lend_farmlands do
    resources :favorites, only: %i[create destroy]
  end
  resources :rent_farmlands
  resources :consults, only: %i[index create show]
end

app/models/notification.rb
class Notification < ApplicationRecord
  # 気になる農地のお知らせが届くようにする
  default_scope -> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
  belongs_to :visitor, class_name: 'User',
                       foreign_key: 'visitor_id',
                       optional: true
  belongs_to :visited, class_name: 'User',
                       foreign_key: 'visited_id',
                       optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :login_required

  def index
    @notifications = current_user.passive_notifications.where.not(visitor_id: current_user.id).where(checked: false).page(params[:page]).per(10)
  end

  def update
    if current_user.passive_notifications.update_all(checked: true)
      redirect_to root_path
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_index.html.erb
<% notifications = @notifications.where.not(visitor_id: current_user.id) %>
<% if notifications.exists? %>
  <%= render notifications %>
  <%= paginate notifications %>
<% else %>
  <p>通知はありません</p>
<% end %>

app/views/notifications/_notification.html.erb
 <%# モデルに書くべきコードはモデルに。コントローラに書くべきコードはコントローラに。全体要リファクタリング %>
<% if notification.checked == false %>
  <% visitor = notification.visitor %>
  <% visited = notification.visited %>
  <div class="form-inline">
    <span>
      <%= link_to user_path(visitor) do %>
        <% if visitor.avatar.nil? %>
          <div class="chat-message__partner-default-img .faceicon">
            <img src="/assets/profile_default_img_128.png" class="chat-default-avatar">
          </div>
        <% else %>
          <%= image_tag visitor.avatar, class: "chat-avatar" %>
        <% end %>
      <% end %>
      <strong class="notification-name">
        <%= visitor.name %>
      </strong>
      <%= 'さんが' %>
      <% case notification.action %>
      <% when 'follow' then %>
      <%= 'あなたをフォローしました' %>
      <% when 'like' then %>
      <%= link_to 'あなたの投稿', notification.post, style: "font-weight: bold;" %>
      <%= 'にいいねしました' %>
      <% when 'comment' then %>
      <% if notification.post.user_id == visited.id %>
        <%= link_to 'あなたの投稿', notification.post, style: "font-weight: bold;" %>
      <% else %>
        <%= link_to post_path(notification.post) do %>
          <% if notification.avatar.nil? %>
            <%# icon_miniとかにクラスを統一する %>
            <div class="chat-message__partner-default-img .faceicon">
              <img src="/assets/profile_default_img_128.png" class="chat-default-avatar">
            </div>
          <% else %>
            <%= image_tag notification.avatar, class: "chat-avatar" %>
          <% end %>
          <strong>
            <%= notification.post.user.name + 'さんの投稿' %>
          </strong>
        <% end %>
      <% end %>
      <%= 'にコメントしました' %>
      <p class="text-muted notification-remark mb-0">
        <%= Comment.find_by(id: notification.comment_id)&.remark %>
      </p>
    <% end %>
  </span>
</div>
<div class="text-muted notification-time">
  <%= time_ago_in_words(notification.created_at).upcase %>
</div>
<hr>
<% end %>

app/views/notifications/index.html.erb
<% notifications = @notifications.where.not(visitor_id: current_user.id) %>
<% if notifications.exists? %>
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3  notifications-bc">
        <%= render @notifications %>
        <%= link_to 'お知らせをすべて削除する', notification_path(@notifications.ids), method: :put, class: "btn btn-dark already-read" %>
        <%= paginate @notifications %>
      </div>
    </div>
  </div>
<% end %>