config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get  '/about',            to: 'static_pages#about'
  get  '/contact',          to: 'static_pages#contact'
  get  '/privacy_policy',   to: 'static_pages#privacy_policy'
  get  '/terms_of_service', to: 'static_pages#terms_of_service'
  get  '/signup',           to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get    :withdrawal_confirmation, :following, :followers
      delete :withdrawal_destroy
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :posts, only: %i[index show create destroy] do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
  resources :relationships, only: %i[create destroy]
  resources :matching, only: [:index]
  resources :chat_rooms, only: %i[create show]
  resources :notifications, only: %i[index update]
  resources :lend_farmlands do
    resources :favorites, only: %i[create destroy]
  end
  resources :rent_farmlands
  resources :consults, only: %i[index create show]
end

app/views/shared/_avatar.html.erb
<% if user.avatar.attached? %>
  <%= image_tag user.avatar, class: "avatar" %>
<% else %>
  <img src="/assets/profile_default_img_128.png" class="default-avatar">
<% end %>

app/views/shared/_chat_index.html.erb
<% provide(:title, 'Chat members') %>
<% if controller_name == 'consults' %>
  <h1>Cosults chat members</h1>
<% elsif controller_name == 'matchings' %>
  <h1>Chat members</h1>
<% end %>
<div class="container">
  <div class="matching-index-page">
    <%#= render "partial/navbar" %>
    <div class="matching">
      <h4 class="matching-num">チャットできるメンバー <%= users.size %>人</h4>
      <div class="matching__list">
        <% unless users.empty? %>
          <% users.each do |user| %>
            <%= link_to consults_path(params: { user_id: user.id }), method: :post do %>
              <div class="matching__person">
                <%= render partial: 'users/user', locals: { user: user } %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    入力内容を確認してください
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <div class="posts">
    <%= render @feed_items %>
  </div>
  <%= paginate @feed_items, param_name: 'feed_page'%>
<% end %>

app/views/shared/_post_attached.html.erb
<div class="card-group">
  <div class="card-body">
    <ul class="list-group list-group-horizontal post-attached">
      <li class="list-group-item flex-fill likes-count">
        <%= render partial: 'likes/like', locals: { post: @post } %>
      </li>
      <li class="list-group-item flex-fill comment-count">
        コメント&nbsp;<%= @post.comments.count %>
      </li>
      <li class="list-group-item flex-fill">
        <%= time_ago_in_words(@post.created_at) %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_post_form.html.erb
<div class="card-group">
  <div class="card-body post-new">
    <h5><%= @current_user.name %></h5>
    <%= render 'shared/stats' %>
    <br>
    <%= form_with(model: @post, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="post-new">
      <%= f.text_area :content, placeholder:  'ここに記事を書く' %>
    </div>
    <%= f.label :画像を追加する %>
    <%= f.file_field :articles_image, accept: "image/jpeg,image/gif,image/png" %>
    <br><br>
    <%= f.submit "Post", class: "btn btn-dark" %>
    <% end %>
  </div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>